-- 004_seed_name_master.sql（db/seed/name_master.seed.json から生成）
-- 生成元: db/build-name-seed-sql.py
INSERT INTO name_master (name, reading, char_type, targets, genders, categories) VALUES
('モモ', 'もも', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい', '食べ物']),
('ココ', 'ここ', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('マロン', 'まろん', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かわいい', '食べ物']),
('チョコ', 'ちょこ', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かわいい', '食べ物']),
('プリン', 'ぷりん', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい', '食べ物']),
('くるみ', 'くるみ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい', '食べ物']),
('みるく', 'みるく', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい', '食べ物']),
('ラテ', 'らて', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かわいい', '食べ物']),
('マメ', 'まめ', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かわいい', '食べ物']),
('うに', 'うに', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かわいい', '食べ物']),
('こむぎ', 'こむぎ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい', '食べ物']),
('あずき', 'あずき', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい', '食べ物']),
('すず', 'すず', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('もこ', 'もこ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('ぷりん', 'ぷりん', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('ぽぽ', 'ぽぽ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('むく', 'むく', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('ゆず', 'ゆず', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい', '食べ物']),
('れもん', 'れもん', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい', '食べ物']),
('みかん', 'みかん', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい', '食べ物']),
('いちご', 'いちご', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい', '食べ物']),
('めろん', 'めろん', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい', '食べ物']),
('ばなな', 'ばなな', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい', '食べ物']),
('さくらんぼ', 'さくらんぼ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('あめ', 'あめ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい', '食べ物']),
('きゃんでぃ', 'きゃんでぃ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい', '食べ物']),
('くっきー', 'くっきー', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい', '食べ物']),
('まかろん', 'まかろん', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい', '食べ物']),
('わっふる', 'わっふる', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい', '食べ物']),
('ぷちこ', 'ぷちこ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('ちゃちゃ', 'ちゃちゃ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('ぷく', 'ぷく', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('ぽん', 'ぽん', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('なな', 'なな', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('ここあ', 'ここあ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい', '食べ物']),
('もか', 'もか', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かわいい', '食べ物']),
('もなか', 'もなか', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かわいい', '食べ物']),
('おはぎ', 'おはぎ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい', '食べ物']),
('だんご', 'だんご', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かわいい', '食べ物']),
('わらび', 'わらび', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かわいい', '食べ物']),
('ぷりんせす', 'ぷりんせす', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('ぴのこ', 'ぴのこ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('こつぶ', 'こつぶ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かわいい']),
('ちび', 'ちび', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かわいい']),
('ぺぺ', 'ぺぺ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かわいい']),
('まりも', 'まりも', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かわいい']),
('こまめ', 'こまめ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かわいい']),
('ぽむ', 'ぽむ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かわいい']),
('むぎゅ', 'むぎゅ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('レオ', 'れお', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('リク', 'りく', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かっこいい']),
('ソラ', 'そら', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かっこいい']),
('ジャック', 'じゃっく', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('マックス', 'まっくす', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('ロイ', 'ろい', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('ノア', 'のあ', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かっこいい']),
('カイ', 'かい', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かっこいい']),
('ゲン', 'げん', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('ライ', 'らい', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('シロ', 'しろ', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かっこいい']),
('クロ', 'くろ', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かっこいい']),
('テツ', 'てつ', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('リオ', 'りお', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かっこいい']),
('ルーク', 'るーく', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('ボス', 'ぼす', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('ゼウス', 'ぜうす', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('コテツ', 'こてつ', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('タロウ', 'たろう', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('ジロウ', 'じろう', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('レックス', 'れっくす', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('ロッキー', 'ろっきー', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('バロン', 'ばろん', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('アレックス', 'あれっくす', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('チャンプ', 'ちゃんぷ', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('ブレイブ', 'ぶれいぶ', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かっこいい']),
('ハンター', 'はんたー', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('ダッシュ', 'だっしゅ', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かっこいい']),
('ジーク', 'じーく', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('ヴァン', 'ゔぁん', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('カイザー', 'かいざー', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('レン', 'れん', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('ジン', 'じん', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('ハク', 'はく', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かっこいい']),
('ヤマト', 'やまと', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('リュウ', 'りゅう', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('ソウ', 'そう', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かっこいい']),
('ガク', 'がく', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かっこいい']),
('ケン', 'けん', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('トラ', 'とら', 'katakana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('さくら', 'さくら', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風', '自然']),
('こはる', 'こはる', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風', '自然']),
('うめ', 'うめ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風', '自然']),
('きく', 'きく', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風', '自然']),
('もみじ', 'もみじ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['和風', '自然']),
('つくし', 'つくし', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['和風', '自然']),
('げんき', 'げんき', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['和風']),
('こごろう', 'こごろう', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['和風']),
('はち', 'はち', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['和風']),
('ふじ', 'ふじ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['和風', '自然']),
('こなつ', 'こなつ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['和風', '自然']),
('なごみ', 'なごみ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['和風']),
('こまち', 'こまち', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風']),
('つばき', 'つばき', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風', '自然']),
('あやめ', 'あやめ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風', '自然']),
('すみれ', 'すみれ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風', '自然']),
('ふうた', 'ふうた', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['和風']),
('そうた', 'そうた', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['和風']),
('はると', 'はると', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['和風']),
('りん', 'りん', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風']),
('あおい', 'あおい', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風', '自然']),
('ひなた', 'ひなた', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['和風', '自然']),
('こはく', 'こはく', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風']),
('ちとせ', 'ちとせ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風']),
('やえ', 'やえ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風']),
('こゆき', 'こゆき', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風']),
('ぼたん', 'ぼたん', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風']),
('つむぎ', 'つむぎ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風']),
('ちより', 'ちより', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風']),
('かえで', 'かえで', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風', '自然']),
('いろは', 'いろは', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風']),
('なずな', 'なずな', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風', '自然']),
('ことね', 'ことね', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風']),
('しの', 'しの', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風']),
('みやび', 'みやび', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風']),
('わこ', 'わこ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風']),
('たまき', 'たまき', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風']),
('そら', 'そら', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('うみ', 'うみ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('ゆき', 'ゆき', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('はる', 'はる', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('なつ', 'なつ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('あき', 'あき', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('ほし', 'ほし', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('つき', 'つき', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('みどり', 'みどり', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('あお', 'あお', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('みなと', 'みなと', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('かぜ', 'かぜ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('なぎ', 'なぎ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('すい', 'すい', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('りく', 'りく', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('こだま', 'こだま', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('しずく', 'しずく', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('ひかり', 'ひかり', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('あさひ', 'あさひ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('ゆうひ', 'ゆうひ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('こもれび', 'こもれび', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('にじ', 'にじ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('くも', 'くも', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('ゆら', 'ゆら', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('なみ', 'なみ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('もり', 'もり', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('いずみ', 'いずみ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('たき', 'たき', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然']),
('ぽち', 'ぽち', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['ユニーク']),
('たま', 'たま', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['ユニーク']),
('みけ', 'みけ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['ユニーク']),
('くろすけ', 'くろすけ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['ユニーク']),
('しろた', 'しろた', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['ユニーク']),
('むぎまる', 'むぎまる', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['ユニーク']),
('ぽんず', 'ぽんず', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['食べ物', 'ユニーク']),
('でこ', 'でこ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['ユニーク']),
('ちくわ', 'ちくわ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['食べ物', 'ユニーク']),
('はんぺん', 'はんぺん', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['食べ物', 'ユニーク']),
('こんぶ', 'こんぶ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['食べ物', 'ユニーク']),
('おもち', 'おもち', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['食べ物', 'ユニーク']),
('まめすけ', 'まめすけ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['食べ物', 'ユニーク']),
('ごまお', 'ごまお', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['食べ物', 'ユニーク']),
('うどん', 'うどん', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['食べ物', 'ユニーク']),
('そうめん', 'そうめん', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['食べ物', 'ユニーク']),
('なめこ', 'なめこ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['ユニーク']),
('ぷりんちゃん', 'ぷりんちゃん', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['ユニーク']),
('べる', 'べる', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('ちゃこ', 'ちゃこ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かわいい']),
('ぴーす', 'ぴーす', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['ユニーク']),
('らっきー', 'らっきー', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かわいい']),
('はっぴー', 'はっぴー', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['かわいい']),
('くう', 'くう', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['ユニーク']),
('ぷう', 'ぷう', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['ユニーク']),
('ふぁん', 'ふぁん', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['ユニーク']),
('めい', 'めい', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('るる', 'るる', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('のえる', 'のえる', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('みや', 'みや', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('びび', 'びび', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('ここみ', 'ここみ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('らむ', 'らむ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('くれあ', 'くれあ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('えま', 'えま', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('そふぃあ', 'そふぃあ', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['かわいい']),
('おりお', 'おりお', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['ユニーク']),
('もかろん', 'もかろん', 'hiragana', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['食べ物', 'ユニーク']),
('空', 'そら', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然', 'かっこいい', '和風']),
('海', 'うみ', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然', 'かっこいい', '和風']),
('陽', 'ひなた', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然', 'かっこいい', '和風']),
('光', 'ひかり', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然', 'かっこいい']),
('福', 'ふく', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['和風', 'かわいい']),
('桜', 'さくら', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風', '自然', 'かわいい']),
('花', 'はな', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風', '自然', 'かわいい']),
('星', 'ほし', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然', 'かわいい']),
('風', 'かぜ', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然', 'かっこいい', '和風']),
('虎', 'とら', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい', '和風']),
('竜', 'りゅう', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい', '和風']),
('音', 'おと', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['和風', 'かわいい']),
('小太郎', 'こたろう', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['和風', 'かっこいい']),
('大和', 'やまと', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['和風', 'かっこいい']),
('小雪', 'こゆき', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風', '自然', 'かわいい']),
('小豆', 'あずき', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['和風', '食べ物', 'かわいい']),
('月', 'つき', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['自然', '和風']),
('雪', 'ゆき', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['自然', '和風', 'かわいい']),
('楓', 'かえで', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['neutral'], ARRAY['自然', '和風']),
('柚', 'ゆず', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['female', 'neutral'], ARRAY['自然', '和風', 'かわいい']),
('蘭', 'らん', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風', 'かわいい']),
('凛', 'りん', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['female'], ARRAY['和風', 'かっこいい']),
('駆', 'かける', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['かっこいい']),
('嵐', 'あらし', 'kanji', ARRAY['dog', 'cat', 'small'], ARRAY['male'], ARRAY['自然', 'かっこいい'])
ON CONFLICT (name) DO UPDATE SET
  reading = EXCLUDED.reading,
  char_type = EXCLUDED.char_type,
  targets = EXCLUDED.targets,
  genders = EXCLUDED.genders,
  categories = EXCLUDED.categories;
