-- ============================================================
-- 命名サービス Neonセットアップ用SQL（コピペ1本）
-- NeonのSQL Editorにこのファイルの中身を全部貼り付けて Run するだけ。
-- 何度実行しても同じ結果になります（IF NOT EXISTS / ON CONFLICT）。
-- ============================================================

-- 001_character_master.sql
-- Phase1（MVP）で必要な唯一のテーブル。
-- 診断結果は永続化しない。書き込みは「未知文字の kanjiapi.dev キャッシュ」のみ（source='kanjiapi'）。

CREATE TABLE IF NOT EXISTS character_master (
  character_id   SERIAL PRIMARY KEY,
  character      TEXT NOT NULL UNIQUE,           -- 1文字
  stroke_count   INTEGER NOT NULL CHECK (stroke_count > 0),
  character_type TEXT NOT NULL
                 CHECK (character_type IN ('kanji','hiragana','katakana','roman','symbol')),
  source         TEXT NOT NULL DEFAULT 'seed'
                 CHECK (source IN ('seed','kanjiapi'))
);

CREATE INDEX IF NOT EXISTS idx_character_master_character
  ON character_master (character);

-- 002_seed_character_master.sql（db/seed/character_master.seed.json から生成）
-- 生成元スクリプト: db/build-seed-sql.py
INSERT INTO character_master (character, stroke_count, character_type, source) VALUES
('あ', 3, 'hiragana', 'seed'),
('い', 2, 'hiragana', 'seed'),
('う', 2, 'hiragana', 'seed'),
('え', 2, 'hiragana', 'seed'),
('お', 3, 'hiragana', 'seed'),
('か', 3, 'hiragana', 'seed'),
('き', 4, 'hiragana', 'seed'),
('く', 1, 'hiragana', 'seed'),
('け', 3, 'hiragana', 'seed'),
('こ', 2, 'hiragana', 'seed'),
('さ', 3, 'hiragana', 'seed'),
('し', 1, 'hiragana', 'seed'),
('す', 2, 'hiragana', 'seed'),
('せ', 3, 'hiragana', 'seed'),
('そ', 2, 'hiragana', 'seed'),
('た', 4, 'hiragana', 'seed'),
('ち', 3, 'hiragana', 'seed'),
('つ', 1, 'hiragana', 'seed'),
('て', 1, 'hiragana', 'seed'),
('と', 2, 'hiragana', 'seed'),
('な', 4, 'hiragana', 'seed'),
('に', 3, 'hiragana', 'seed'),
('ぬ', 2, 'hiragana', 'seed'),
('ね', 2, 'hiragana', 'seed'),
('の', 1, 'hiragana', 'seed'),
('は', 3, 'hiragana', 'seed'),
('ひ', 1, 'hiragana', 'seed'),
('ふ', 4, 'hiragana', 'seed'),
('へ', 1, 'hiragana', 'seed'),
('ほ', 4, 'hiragana', 'seed'),
('ま', 3, 'hiragana', 'seed'),
('み', 2, 'hiragana', 'seed'),
('む', 3, 'hiragana', 'seed'),
('め', 2, 'hiragana', 'seed'),
('も', 3, 'hiragana', 'seed'),
('や', 3, 'hiragana', 'seed'),
('ゆ', 2, 'hiragana', 'seed'),
('よ', 2, 'hiragana', 'seed'),
('ら', 2, 'hiragana', 'seed'),
('り', 2, 'hiragana', 'seed'),
('る', 2, 'hiragana', 'seed'),
('れ', 2, 'hiragana', 'seed'),
('ろ', 1, 'hiragana', 'seed'),
('わ', 2, 'hiragana', 'seed'),
('を', 3, 'hiragana', 'seed'),
('ん', 1, 'hiragana', 'seed'),
('ア', 2, 'katakana', 'seed'),
('イ', 2, 'katakana', 'seed'),
('ウ', 3, 'katakana', 'seed'),
('エ', 3, 'katakana', 'seed'),
('オ', 3, 'katakana', 'seed'),
('カ', 2, 'katakana', 'seed'),
('キ', 3, 'katakana', 'seed'),
('ク', 2, 'katakana', 'seed'),
('ケ', 3, 'katakana', 'seed'),
('コ', 2, 'katakana', 'seed'),
('サ', 3, 'katakana', 'seed'),
('シ', 3, 'katakana', 'seed'),
('ス', 2, 'katakana', 'seed'),
('セ', 2, 'katakana', 'seed'),
('ソ', 2, 'katakana', 'seed'),
('タ', 3, 'katakana', 'seed'),
('チ', 3, 'katakana', 'seed'),
('ツ', 3, 'katakana', 'seed'),
('テ', 3, 'katakana', 'seed'),
('ト', 2, 'katakana', 'seed'),
('ナ', 2, 'katakana', 'seed'),
('ニ', 2, 'katakana', 'seed'),
('ヌ', 2, 'katakana', 'seed'),
('ネ', 4, 'katakana', 'seed'),
('ノ', 1, 'katakana', 'seed'),
('ハ', 2, 'katakana', 'seed'),
('ヒ', 2, 'katakana', 'seed'),
('フ', 1, 'katakana', 'seed'),
('ヘ', 1, 'katakana', 'seed'),
('ホ', 4, 'katakana', 'seed'),
('マ', 2, 'katakana', 'seed'),
('ミ', 3, 'katakana', 'seed'),
('ム', 2, 'katakana', 'seed'),
('メ', 2, 'katakana', 'seed'),
('モ', 3, 'katakana', 'seed'),
('ヤ', 2, 'katakana', 'seed'),
('ユ', 2, 'katakana', 'seed'),
('ヨ', 3, 'katakana', 'seed'),
('ラ', 2, 'katakana', 'seed'),
('リ', 2, 'katakana', 'seed'),
('ル', 2, 'katakana', 'seed'),
('レ', 1, 'katakana', 'seed'),
('ロ', 3, 'katakana', 'seed'),
('ワ', 2, 'katakana', 'seed'),
('ヲ', 3, 'katakana', 'seed'),
('ン', 2, 'katakana', 'seed'),
('ー', 1, 'katakana', 'seed'),
('山', 3, 'kanji', 'seed'),
('田', 5, 'kanji', 'seed'),
('太', 4, 'kanji', 'seed'),
('郎', 9, 'kanji', 'seed'),
('川', 3, 'kanji', 'seed'),
('木', 4, 'kanji', 'seed'),
('林', 8, 'kanji', 'seed'),
('森', 12, 'kanji', 'seed'),
('石', 5, 'kanji', 'seed'),
('本', 5, 'kanji', 'seed'),
('一', 1, 'kanji', 'seed'),
('二', 2, 'kanji', 'seed'),
('三', 3, 'kanji', 'seed'),
('四', 5, 'kanji', 'seed'),
('五', 4, 'kanji', 'seed'),
('六', 4, 'kanji', 'seed'),
('七', 2, 'kanji', 'seed'),
('八', 2, 'kanji', 'seed'),
('九', 2, 'kanji', 'seed'),
('十', 2, 'kanji', 'seed'),
('人', 2, 'kanji', 'seed'),
('大', 3, 'kanji', 'seed'),
('小', 3, 'kanji', 'seed'),
('上', 3, 'kanji', 'seed'),
('下', 3, 'kanji', 'seed'),
('中', 4, 'kanji', 'seed'),
('日', 4, 'kanji', 'seed'),
('月', 4, 'kanji', 'seed'),
('火', 4, 'kanji', 'seed'),
('水', 4, 'kanji', 'seed'),
('金', 8, 'kanji', 'seed'),
('土', 3, 'kanji', 'seed'),
('子', 3, 'kanji', 'seed'),
('女', 3, 'kanji', 'seed'),
('男', 7, 'kanji', 'seed'),
('名', 6, 'kanji', 'seed'),
('前', 9, 'kanji', 'seed'),
('字', 6, 'kanji', 'seed'),
('学', 8, 'kanji', 'seed'),
('生', 5, 'kanji', 'seed'),
('花', 10, 'kanji', 'seed'),
('海', 10, 'kanji', 'seed'),
('空', 8, 'kanji', 'seed'),
('星', 9, 'kanji', 'seed'),
('光', 6, 'kanji', 'seed'),
('愛', 13, 'kanji', 'seed'),
('心', 4, 'kanji', 'seed'),
('和', 8, 'kanji', 'seed'),
('平', 5, 'kanji', 'seed'),
('安', 6, 'kanji', 'seed'),
('美', 9, 'kanji', 'seed'),
('優', 17, 'kanji', 'seed'),
('健', 11, 'kanji', 'seed'),
('翔', 12, 'kanji', 'seed'),
('樹', 16, 'kanji', 'seed'),
('結', 12, 'kanji', 'seed'),
('莉', 13, 'kanji', 'seed'),
('陽', 17, 'kanji', 'seed'),
('介', 4, 'kanji', 'seed'),
('池', 7, 'kanji', 'seed'),
('打', 6, 'kanji', 'seed'),
('草', 12, 'kanji', 'seed')
ON CONFLICT (character) DO NOTHING;

-- 確認用（任意）: 登録件数とサンプル
SELECT count(*) AS 登録文字数 FROM character_master;
SELECT character, stroke_count FROM character_master WHERE character IN ('山','田','太','郎');
